### ISSUE TITLE
Further development of period/product config page

### ISSUE THREAD

**Issue by MarkWPeter** [FoodCoopX/wirgarten-tapir#81]
continuation of issue #44 

Page with base CRUD functionality is implemented.

Incomplete list of Todos (it will be continued after product owner feedback):

1. **General**
   - [ ] ~Confirm delete modal~ (handled in #140)

2. **Growing Period**
   - [x] from < to
   - [x] no overlap
   - [ ] no gap (TBD: show a warning or completely dissallow?)
   - [x] grey out old growing periods
   - [x] mark current growing period
   - [x] mark upcoming growing periods
   - [ ] show warning if no upcoming growing period is defined
   

3. **Product Types/Capacities**
   - [ ] tax rate input must be in percent
   - [ ] product capacity must be configurable via number of equivalents (follows #105)
   - [x] editable or deletable only if it is in the future

4. **Product**
   - [ ] price should be in equivalents (e.g. 0.5 M-Anteile, follows #105)

--- NEW

5. Delivery Exception UI:
   - [ ]  `DeliveryException` CRUD (TBD)
